"""empty message

Revision ID: 17a375cb2484
Revises: a089f8b9722d
Create Date: 2025-02-17 11:11:56.021754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a375cb2484'
down_revision = 'a089f8b9722d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.String(), nullable=False))
        batch_op.drop_column('papulation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('papulation', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('population')

    # ### end Alembic commands ###
